feat: Add linting configuration to GitHub Actions (#21)
## Description

Currently GitHub Actions only run formatting but not linting. We want to
enable linting to ensure the code quality of the repository.

## Changes Made

- Add prettier dependency to each microservices - so it is possible to
run formatting without running `npm install` at root directory.
- Add Linting Checks to Github Actions for each microservice in
`format-lint.yml`

## To Note (for Developers)
- Need to add a new job for each new microservice in 

## Before Merging
- Fix all lint issues in the repo (Merge #22 before merging this PR!) -
_Update: Already merged!_

## Test
Any linting issues could be viewed in the `Files changed` tab. 
Example of a sample lint failure. 
<img width="614" height="350" alt="image"
src="https://github.com/user-attachments/assets/a6d82339-3667-45a9-9ab4-aae63ef76eb2"
/>

diff --git a/.github/workflows/format-lint.yml b/.github/workflows/format-lint.yml
--- a/.github/workflows/format-lint.yml
+++ b/.github/workflows/format-lint.yml
@@ -1,15 +1,15 @@
-name: Formatting and Linting Checks
+name: Format & Lint Microservices
 
 on:
   push:
     branches:
-      - master
+      - main
   pull_request:
     branches:
       - "**"
 
 jobs:
-  prettier:
+  format-check-all:
     runs-on: ubuntu-latest
 
     steps:
@@ -26,3 +26,238 @@ jobs:
 
       - name: Run Prettier Checks
         run: npm run format:check
+
+  matching-ui-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set REVIEWDOG_GITHUB_API_TOKEN
+        run: echo "REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}" >> $GITHUB_ENV
+
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20.x"
+          cache: "npm"
+
+      - name: Install dependencies
+        run: |
+          cd ./ui-services/matching-ui-service
+          npm install --frozen-lockfile
+
+      - name: Install reviewdog
+        uses: reviewdog/action-setup@v1
+        with:
+          reviewdog_version: latest
+
+      - name: Run ESLint and Reviewdog
+        run: |
+          cd ./ui-services/matching-ui-service
+          npx eslint . || exit_code=$?
+          eslint_exit_code=$exit_code
+
+          if [ $eslint_exit_code -ne 0 ]; then
+            echo "ESLint failed for matching-ui"
+            exit 1
+          fi
+
+          npx eslint --format json . > eslint-report.json
+          cat eslint-report.json | reviewdog -f=eslint -name="eslint" -reporter=github-pr-review -level=error
+
+  questions-ui-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set REVIEWDOG_GITHUB_API_TOKEN
+        run: echo "REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}" >> $GITHUB_ENV
+
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20.x"
+          cache: "npm"
+
+      - name: Install dependencies
+        run: |
+          cd ./ui-services/question-ui-service
+          npm install --frozen-lockfile
+
+      - name: Install reviewdog
+        uses: reviewdog/action-setup@v1
+        with:
+          reviewdog_version: latest
+
+      - name: Run ESLint and Reviewdog
+        run: |
+          cd ./ui-services/question-ui-service
+          exit_code=0
+          npx eslint . || exit_code=$?
+          eslint_exit_code=$exit_code
+
+          if [ $eslint_exit_code -ne 0 ]; then
+            echo "ESLint failed for questions-ui"
+            exit 1
+          fi
+
+          npx eslint --format json . > eslint-report.json
+          cat eslint-report.json | reviewdog -f=eslint -name="eslint" -reporter=github-pr-review -level=error
+
+  collab-ui-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set REVIEWDOG_GITHUB_API_TOKEN
+        run: echo "REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}" >> $GITHUB_ENV
+
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20.x"
+          cache: "npm"
+
+      - name: Install dependencies
+        run: |
+          cd ./ui-services/collab-ui-service
+          npm install --frozen-lockfile
+
+      - name: Install reviewdog
+        uses: reviewdog/action-setup@v1
+        with:
+          reviewdog_version: latest
+
+      - name: Run ESLint and Reviewdog
+        run: |
+          cd ./ui-services/collab-ui-service
+          npx eslint . || exit_code=$?
+          eslint_exit_code=$exit_code
+
+          if [ $eslint_exit_code -ne 0 ]; then
+            echo "ESLint failed for collab-ui"
+            exit 1
+          fi
+
+          npx eslint --format json . > eslint-report.json
+          cat eslint-report.json | reviewdog -f=eslint -name="eslint" -reporter=github-pr-review -level=error
+
+  user-ui-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set REVIEWDOG_GITHUB_API_TOKEN
+        run: echo "REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}" >> $GITHUB_ENV
+
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20.x"
+          cache: "npm"
+
+      - name: Install dependencies
+        run: |
+          cd ./ui-services/user-ui-service
+          npm install --frozen-lockfile
+
+      - name: Install reviewdog
+        uses: reviewdog/action-setup@v1
+        with:
+          reviewdog_version: latest
+
+      - name: Run ESLint and Reviewdog
+        run: |
+          cd ./ui-services/user-ui-service
+          npx eslint . || exit_code=$?
+          eslint_exit_code=$exit_code
+
+          if [ $eslint_exit_code -ne 0 ]; then
+            echo "ESLint failed for questions-ui"
+            exit 1
+          fi
+
+          npx eslint --format json . > eslint-report.json
+          cat eslint-report.json | reviewdog -f=eslint -name="eslint" -reporter=github-pr-review -level=error
+
+  history-ui-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set REVIEWDOG_GITHUB_API_TOKEN
+        run: echo "REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}" >> $GITHUB_ENV
+
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20.x"
+          cache: "npm"
+
+      - name: Install dependencies
+        run: |
+          cd ./ui-services/history-ui-service
+          npm install --frozen-lockfile
+
+      - name: Install reviewdog
+        uses: reviewdog/action-setup@v1
+        with:
+          reviewdog_version: latest
+
+      - name: Run ESLint and Reviewdog
+        run: |
+          cd ./ui-services/history-ui-service
+          npx eslint . || exit_code=$?
+          eslint_exit_code=$exit_code
+
+          if [ $eslint_exit_code -ne 0 ]; then
+            echo "ESLint failed for collab-ui"
+            exit 1
+          fi
+
+          npx eslint --format json . > eslint-report.json
+          cat eslint-report.json | reviewdog -f=eslint -name="eslint" -reporter=github-pr-review -level=error
+
+  ui-shell-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set REVIEWDOG_GITHUB_API_TOKEN
+        run: echo "REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}" >> $GITHUB_ENV
+
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20.x"
+          cache: "npm"
+
+      - name: Install dependencies
+        run: |
+          cd ./ui-shell
+          npm install --frozen-lockfile
+
+      - name: Install reviewdog
+        uses: reviewdog/action-setup@v1
+        with:
+          reviewdog_version: latest
+
+      - name: Run ESLint and Reviewdog
+        run: |
+          cd ./ui-shell
+          npx eslint . || exit_code=$?
+          eslint_exit_code=$exit_code
+
+          if [ $eslint_exit_code -ne 0 ]; then
+            echo "ESLint failed for collab-ui"
+            exit 1
+          fi
+
+          npx eslint --format json . > eslint-report.json
+          cat eslint-report.json | reviewdog -f=eslint -name="eslint" -reporter=github-pr-review -level=error
